### ISSUE TITLE
Suggestion: GitLab Support

### ISSUE THREAD

**Issue by ShakataGaNai** [go-playground/webhooks#1]
The title is fairly self explanatory but I think it would be great to add [GitLab Webhook](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md) support to round out the collection of very popular Git-software.

**Comment by joeybloggs** [comment]
Hey @ShakataGaNai 

thanks for you suggestion, it doesn't look that hard, just have to create the structs for each event type and basically copy-paste-modify the github code.

It may take me a long while to get to this though, any help/pull requests would definitely be appreciated ( just having trouble finding the time ); but I will evently get to it if not 😄

**Comment by joeybloggs** [comment]
@ShakataGaNai GitLab support has finally been added :)

please see [Release 2.1.0](https://github.com/go-playground/webhooks/releases/tag/v2.1.0)

if you have any problems with it just let me know :+1:
