### ISSUE TITLE
[GitHub] Check HMAC signature in SHA256

### ISSUE THREAD

**Issue by tisonkun** [go-playground/webhooks#143]
I don't know whether it's a nit win migrated from SHA1, but it's compatible and recommended at [GitHub Docs](https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks).

I'm glad to send a PR if it's concluded to be a valid issue.

**Comment by tisonkun** [comment]
Closed as no one interested in.

**Comment by dinvlad** [comment]
We're interested, please reopen

**Comment by tisonkun** [comment]
@dinvlad Thanks for your reply. For no one, I mean no one from the maintainers and thus I cannot make progress. If you're interested to report it as an issue and keep track on it, you can create a new issue. I just don't use this library any more and don't want to keep such an open issue.
