### ISSUE TITLE
gogs

### ISSUE THREAD

**Issue by reqshark** [go-playground/webhooks#15]
any interest here in adding support for gog webhooks?

lets user set webhook on the org, plus crazy good perf

https://github.com/gogits/gogs

**Comment by joeybloggs** [comment]
Hey @reqshark 

sure I'd be interested, I can't promise it tomorrow or anything,  times spread pretty thin right now, but if you or anyone could help or point me in the direction of the webhook API code that'd help speed things be along :)

**Comment by naiba** [comment]
@reqshark @joeybloggs #29
