### ISSUE TITLE
Github X-GitHub-Delivery Header

### ISSUE THREAD

**Issue by alrs** [go-playground/webhooks#2]
The Github web interface for webhooks shows each webhook request that was sent, along with the request's delivery ID.

This delivery ID is not part of the JSON payload, but rather part of the HTTP headers.

I propose adding a "Delivery" member to each of the payload structs so that this information is available in the webhooks library.

Would you be receptive to a PR that did this?

**Comment by joeybloggs** [comment]
Hey @alrs 

I wasn't aware that info was in the header, I'd definitely accept a pull request only, I think that it might be better to send the http headers as another param to the [ProcessPayloadFunc](https://github.com/go-playground/webhooks/blob/v1/webhooks.go#L37)

that way you'd still have access to the information, but can keep the Payloads just as they are received without any future possibility of a name collision.

I'd have to bump this library to version 2.0.0 for the change, but that's not a big deal.

I'll probably look at this sometime tonight, but if can beat me to it, I'd merge the PR 👍  thanks in advance!

**Comment by alrs** [comment]
Is v2-development the correct branch to make a pull request?

**Comment by joeybloggs** [comment]
Hey @alrs 

I found some time to get this done, and is now available in [release 2.0.0](https://github.com/go-playground/webhooks/releases/tag/v2.0.0)

please let me know if this works for you 😄
