### ISSUE TITLE
Support returning an error to webhook

### ISSUE THREAD

**Issue by discordianfish** [go-playground/webhooks#22]
Hi,

it looks like there is no way for a webhook handler to return an error to the webhook request.
Usually I want to return a failure to whatever is sending the webhook so they can retry it later on.

**Comment by joeybloggs** [comment]
@discordianfish I will try and look into this soon, sorry for the delay, been super busy

**Comment by joeybloggs** [comment]
This is now achieved in v5+, closing :)
