### ISSUE TITLE
Make Logger Interface Compatible with logrus.Logger

### ISSUE THREAD

**Issue by c-Brooks** [go-playground/webhooks#31]
Hi! Love the package, great work guys.

I'm wondering if it's possible to change the Logger interface to be the same as Logrus's Logger interface, which takes variadic interfaces as arguments instead of a single string, like your package. This would not break the API and would be really useful for us, and probably a lot of people since Logrus is pretty ubiquitous.
Have you ever thought about this? Let me know if you can let this change in. I'm happy to make a PR.

Proposed change:
```go

// old interface
type Logger interface {
	Info(string)
	Error(string)
	Debug(string)
}

// new interface
type Logger interface {
	Info(...interface{})
	Error(...interface{})
	Debug(...interface{})
}

```
This allows us to do something like:
```go

func init() {
	log := logrus.StandardLogger()
	log.Out = os.Stdout
	// ... more config ...
	webhooks.DefaultLog = log
}
```

**Comment by joeybloggs** [comment]
@c-Brooks I can see how that would be useful would even work better with my own log package ;)

yes, I would definitely accept a PR, it would have to be a breaking change though as the interface for existing users would fail; not the usage but the default log assignment.

**Comment by c-Brooks** [comment]
v4 works like a charm, closing this now 👍
