### ISSUE TITLE
Support for multiple webhooks on the same server

### ISSUE THREAD

**Issue by zakkor** [go-playground/webhooks#39]
Hey everyone, I needed support for listening to multiple webhooks on the same server so I wrote an example implementation for bitbucket, which seems to work okay.

#40 

It's not complete or necessarily correct, and it doesn't have tests (yet), but please let me know your thoughts

**Comment by joeybloggs** [comment]
Hey @zakkor I just released v5 and that changes will allow you to accomplish this, see the examples for details.

**Comment by joeybloggs** [comment]
@zakkor please let me know that this works for you and then I can close this out :)
