### ISSUE TITLE
Bitbucket server does not send X-Hook-UUID header

### ISSUE THREAD

**Issue by jadunham1** [go-playground/webhooks#42]
Looks like all other interfaces are the same, but the X-Hook-UUID header never gets set in bitbucket server.
Bitbucket: https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html
Bitbucketserver: https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html#Eventpayload-httpheadersHTTPheaders

It appears the X-Hook-UUID is only used as a comparison if the UUID is actually set.
I'm proposing that we validate that the X-Hook-UUID header exists only if a user sets a value to the secret UUID in the bitbucket config.

**Comment by joeybloggs** [comment]
@jadunham1 solved in release v5.1.0

**Comment by lukepatrick** [comment]
Can you reference a commit/PR for this fix? It's not apparent to me in the code.
