### ISSUE TITLE
Add support for Bitbucket X-Hub-Signature header

### ISSUE THREAD

**Issue by lukepatrick** [go-playground/webhooks#59]
BitBucket Server uses a X-Hub-Signature header value to security in-lieu of the X-Hook-UUID from BitBucket Cloud. Requesting support for the X-Hub-Signature header.

[Bitbucket Server docs](https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html#Eventpayload-httpheadersHTTPheaders)

**Comment by joeybloggs** [comment]
@lukepatrick after a quick glance, it looks like it uses HMAC verification much like GitHub, let me think about the best way to support this :)

**Comment by joeybloggs** [comment]
Added https://github.com/go-playground/webhooks/releases/tag/v5.7.0
