### ISSUE TITLE
Add support for Bitbucket Server

### ISSUE THREAD

**Issue by goober** [go-playground/webhooks#60]
Native support for webhooks was [added in Bitbucket Server 5.4](https://confluence.atlassian.com/bitbucketserver/bitbucket-server-5-4-release-notes-935388966.html)

However, both [payloads and event keys](https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html) differ from the Bitbucket Cloud. So I haven't been able to take advantage of this library. Are there any ongoing work for supporting native webhooks from Bitbucket Server or are there room for improvement?

**Comment by joeybloggs** [comment]
There is no work on the books yet, but it should be as simple as copy pasting the existing implementation and modifying to support BitBucket Server.

Any help with a PR would be great!

**Comment by goober** [comment]
Thanks for quick response, I will see if I can provide a PR during the upcoming week.
