### ISSUE TITLE
Gitlab MergeRequestEvents

### ISSUE THREAD

**Issue by patcable** [go-playground/webhooks#7]
It looks like `MergeRequestEvents` is represented as `MergerRequestEvents` -- I was wondering if the double "r" was intentional? 

I can do a PR to fix but wanted to check first.

**Comment by joeybloggs** [comment]
Nope definitely a typo, a PR request would be great!

I'll merge it later tonight after I get home

**Comment by joeybloggs** [comment]
This should now be Corrected in [Release 3.0.0](https://github.com/go-playground/webhooks/releases/tag/v3.0.0)

**Comment by patcable** [comment]
Ah -- sorry -- I need to clearly update my github notification settings; i just circled back to this now and saw you took care of it. Thank you for the fix!
