### ISSUE TITLE
Position in commit notes no longer int64

### ISSUE THREAD

**Issue by maguro** [go-playground/webhooks#78]
Position in commit notes are now an object.  There are some additional position fields.

    "change_position": {
        "base_sha": null,
        "start_sha": null,
        "head_sha": null,
        "old_path": null,
        "new_path": null,
        "position_type": "text",
        "old_line": null,
        "new_line": null
    },
    "original_position": {
        "base_sha": "068bca55a1606f8deda95713d043daae579123d0",
        "start_sha": "0883f2037428b19cac8bb5ac3823924dff0062e3",
        "head_sha": "130d7c3903d7d015219482fe5ad1b00110e76c4b",
        "old_path": "dataflow/src/main/java/com/nianticproject/lexicon/wb/transforms/ParseSessionTrackingProtos.java",
        "new_path": "dataflow/src/main/java/com/nianticproject/lexicon/wb/transforms/ParseSessionTrackingProtos.java",
        "position_type": "text",
        "old_line": null,
        "new_line": 50
    },
    "position": {
        "base_sha": "068bca55a1606f8deda95713d043daae579123d0",
        "start_sha": "0883f2037428b19cac8bb5ac3823924dff0062e3",
        "head_sha": "130d7c3903d7d015219482fe5ad1b00110e76c4b",
        "old_path": "dataflow/src/main/java/com/nianticproject/lexicon/wb/transforms/ParseSessionTrackingProtos.java",
        "new_path": "dataflow/src/main/java/com/nianticproject/lexicon/wb/transforms/ParseSessionTrackingProtos.java",
        "position_type": "text",
        "old_line": null,
        "new_line": 50
    },

**Comment by deankarn** [comment]
merged PR in release v5.12.0 :)
