### ISSUE TITLE
How to add a custom route to the server?

### ISSUE THREAD

**Issue by shirshir** [go-playground/webhooks#9]
Right now it is not possible to add a custom route to the server, because the HTTP handler is overridden. Is there a way to achieve that? I want to add a route to return a server health check.

**Comment by joeybloggs** [comment]
Hey @shirshir 

Yes you are correct there is currently no way to do that but I see that as a pretty common requirement.

let me think about the best way to expose that functionality and I'll definitely add it.

Off the top of my head, I'd add a new function `Handler` or `HandlerFunc` that would accept the webhook and return an `http.Handler` or `http.HandlerFunc` and then you can handle it with whatever `Mux` you wish.

**Comment by shirshir** [comment]
Thanks Joey! That seems like a good idea. Maybe also have a look at [Alice](https://github.com/justinas/alice).

**Comment by shirshir** [comment]
Thanks for the quick solution, Dean! 👍
