### ISSUE TITLE
GitLab 12.3 incompatibility with pipeline event

### ISSUE THREAD

**Issue by Toshik1978** [go-playground/webhooks#92]
GitLab 12.3 added "source" field to "object_attributes". But it's not as other source fields - it's a simple string. https://gitlab.com/gitlab-org/gitlab-foss/merge_requests/32373
So, webhook now can't unmarshal pipeline event structure.

`json: cannot unmarshal string into Go struct field ObjectAttributes.object_attributes.source of type gitlab.Source`

Looks like it's not trivial changes, because ObjectAttributes structure uses everywhere... That's why I can't simply create PR. May be the only way is to create separate ObjectAtrributesPipeline structure, but looks like it should be maintainer decision.

**Comment by Toshik1978** [comment]
Just in case...
https://github.com/Toshik1978/webhooks/commit/f248671aae807b954c2074e063fac1030917b1b7

**Comment by maguro** [comment]
> Just in case...
> [Toshik1978@f248671](https://github.com/Toshik1978/webhooks/commit/f248671aae807b954c2074e063fac1030917b1b7)

This is how other GitLab API projects are handling this and it seems like a reasonable solution.  Can you submit a PR?

**Comment by Toshik1978** [comment]
@maguro ok, submit PR ) Waiting for maintainer.

**Comment by inful** [comment]
Would it be possible to roll a new release containing this fix?

**Comment by deankarn** [comment]
Sorry all, will try to get to this in the nest couple weeks, jsut very time constrained right now, my appologies.

**Comment by inful** [comment]
@deankarn no problem, thank you for making your work available to the world 👍

**Comment by deankarn** [comment]
Hey @inful @Toshik1978 @maguro 

I've been having a hard time keeping up with all my open source stuff and feel bad not being able to get to this, would any of you be interested in becoming a collaborator on this project?

**Comment by Toshik1978** [comment]
Hi @deankarn

I think I can be collaborator. I'm mostly interested in GitLab/GitHub integration and  I'm not sure, that I'll have time to greatly improve it. But I can support it at least.

**Comment by inful** [comment]
@deankarn I am sorry, but I do not have the available time to provide proper maintenance of the project. I hope there are people out there with more time on their hands, though.

**Comment by deankarn** [comment]
Thanks @Toshik1978 I'll try and set it all up in the coming week.

@inful no problem, thanks for considering :)

**Comment by maguro** [comment]
Sure, sgtm.

**Comment by deankarn** [comment]
@maguro @Toshik1978 I've invited you as collaborators, sorry it's taken this long.
